#pragma once

#include <mc_cpp/nbt/to_compound.hpp>

namespace mc {

    struct GameRules final : ToCompound {
        bool doFireTick{true};
        bool mobGriefing{true};
        bool keepInventory{};
        bool doMobSpawning{true};
        bool doMobLoot{true};
        bool projectilesCanBreakBlocks{true};
        bool doTileDrops{true};
        bool doEntityDrops{true};
        bool commandBlockOutput{true};
        bool naturalRegeneration{true};
        bool doDaylightCycle{true};
        bool logAdminCommands{true};
        bool showDeathMessages{true};
        int32_t randomTickSpeed{3};
        bool sendCommandFeedback{true};
        bool reducedDebugInfo{};
        bool spectatorsGenerateChunks{true};
        int32_t spawnRadius{10};
        bool disablePlayerMovementCheck{};
        bool disableElytraMovementCheck{};
        int32_t maxEntityCramming{24};
        bool doWeatherCycle{true};
        bool doLimitedCrafting{};
        int32_t maxCommandChainLength{65536};
        int32_t maxCommandForkCount{65536};
        int32_t commandModificationBlockLimit{32768};
        bool announceAdvancements{true};
        bool disableRaids{};
        bool doInsomnia{true};
        bool doImmediateRespawn{};
        int32_t playersNetherPortalDefaultDelay{80};
        int32_t playersNetherPortalCreativeDelay{0};
        bool drowningDamage{true};
        bool fallDamage{true};
        bool fireDamage{true};
        bool freezeDamage{true};
        bool doPatrolSpawning{true};
        bool doTraderSpawning{true};
        bool doWardenSpawning{true};
        bool forgiveDeadPlayers{true};
        bool universalAnger{};
        int32_t playersSleepingPercentage{100};
        bool blockExplosionDropDecay{true};
        bool mobExplosionDropDecay{true};
        bool tntExplosionDropDecay{};
        int32_t snowAccumulationHeight{1};
        bool waterSourceConversion{true};
        bool lavaSourceConversion{};
        bool globalSoundEvents{true};
        bool doVinesSpread{true};
        bool enderPearlsVanishOnDeath{true};
        int32_t minecartMaxSpeed{8};
        int32_t spawnChunkRadius{2};

        static auto staticGameRules() -> GameRules {
            GameRules gameRules{};
            gameRules.doFireTick = false;
            gameRules.mobGriefing = false;
            gameRules.doMobSpawning = false;
            gameRules.doMobLoot = false;
            gameRules.projectilesCanBreakBlocks = false;
            gameRules.naturalRegeneration = false;
            gameRules.doDaylightCycle = false;
            gameRules.randomTickSpeed = 0;
            gameRules.spectatorsGenerateChunks = false;
            gameRules.doWeatherCycle = false;
            gameRules.disableRaids = true;
            gameRules.doInsomnia = false;
            gameRules.drowningDamage = false;
            gameRules.fallDamage = false;
            gameRules.fireDamage = false;
            gameRules.freezeDamage = false;
            gameRules.doPatrolSpawning = false;
            gameRules.doTraderSpawning = false;
            gameRules.doWardenSpawning = false;
            gameRules.doVinesSpread = false;
            return gameRules;
        }

        auto writeCompound(const MinecraftRegistry &registry, NbtCompound &compound) const -> void override {
            compound.put("doFireTick", doFireTick);
            compound.put("mobGriefing", mobGriefing);
            compound.put("keepInventory", keepInventory);
            compound.put("doMobSpawning", doMobSpawning);
            compound.put("doMobLoot", doMobLoot);
            compound.put("projectilesCanBreakBlocks", projectilesCanBreakBlocks);
            compound.put("doTileDrops", doTileDrops);
            compound.put("doEntityDrops", doEntityDrops);
            compound.put("commandBlockOutput", commandBlockOutput);
            compound.put("naturalRegeneration", naturalRegeneration);
            compound.put("doDaylightCycle", doDaylightCycle);
            compound.put("logAdminCommands", logAdminCommands);
            compound.put("showDeathMessages", showDeathMessages);
            compound.put("randomTickSpeed", randomTickSpeed);
            compound.put("sendCommandFeedback", sendCommandFeedback);
            compound.put("reducedDebugInfo", reducedDebugInfo);
            compound.put("spectatorsGenerateChunks", spectatorsGenerateChunks);
            compound.put("spawnRadius", spawnRadius);
            compound.put("disablePlayerMovementCheck", disablePlayerMovementCheck);
            compound.put("disableElytraMovementCheck", disableElytraMovementCheck);
            compound.put("maxEntityCramming", maxEntityCramming);
            compound.put("doWeatherCycle", doWeatherCycle);
            compound.put("doLimitedCrafting", doLimitedCrafting);
            compound.put("maxCommandChainLength", maxCommandChainLength);
            compound.put("maxCommandForkCount", maxCommandForkCount);
            compound.put("commandModificationBlockLimit", commandModificationBlockLimit);
            compound.put("announceAdvancements", announceAdvancements);
            compound.put("disableRaids", disableRaids);
            compound.put("doInsomnia", doInsomnia);
            compound.put("doImmediateRespawn", doImmediateRespawn);
            compound.put("playersNetherPortalDefaultDelay", playersNetherPortalDefaultDelay);
            compound.put("playersNetherPortalCreativeDelay", playersNetherPortalCreativeDelay);
            compound.put("drowningDamage", drowningDamage);
            compound.put("fallDamage", fallDamage);
            compound.put("fireDamage", fireDamage);
            compound.put("freezeDamage", freezeDamage);
            compound.put("doPatrolSpawning", doPatrolSpawning);
            compound.put("doTraderSpawning", doTraderSpawning);
            compound.put("doWardenSpawning", doWardenSpawning);
            compound.put("forgiveDeadPlayers", forgiveDeadPlayers);
            compound.put("universalAnger", universalAnger);
            compound.put("playersSleepingPercentage", playersSleepingPercentage);
            compound.put("blockExplosionDropDecay", blockExplosionDropDecay);
            compound.put("mobExplosionDropDecay", mobExplosionDropDecay);
            compound.put("tntExplosionDropDecay", tntExplosionDropDecay);
            compound.put("snowAccumulationHeight", snowAccumulationHeight);
            compound.put("waterSourceConversion", waterSourceConversion);
            compound.put("lavaSourceConversion", lavaSourceConversion);
            compound.put("globalSoundEvents", globalSoundEvents);
            compound.put("doVinesSpread", doVinesSpread);
            compound.put("enderPearlsVanishOnDeath", enderPearlsVanishOnDeath);
            compound.put("minecartMaxSpeed", minecartMaxSpeed);
            compound.put("spawnChunkRadius", spawnChunkRadius);
        }

        auto readCompound(const MinecraftRegistry &registry, const NbtCompound &compound) -> void override {
            compound.read("doFireTick", doFireTick);
            compound.read("mobGriefing", mobGriefing);
            compound.read("keepInventory", keepInventory);
            compound.read("doMobSpawning", doMobSpawning);
            compound.read("doMobLoot", doMobLoot);
            compound.read("projectilesCanBreakBlocks", projectilesCanBreakBlocks);
            compound.read("doTileDrops", doTileDrops);
            compound.read("doEntityDrops", doEntityDrops);
            compound.read("commandBlockOutput", commandBlockOutput);
            compound.read("naturalRegeneration", naturalRegeneration);
            compound.read("doDaylightCycle", doDaylightCycle);
            compound.read("logAdminCommands", logAdminCommands);
            compound.read("showDeathMessages", showDeathMessages);
            compound.read("randomTickSpeed", randomTickSpeed);
            compound.read("sendCommandFeedback", sendCommandFeedback);
            compound.read("reducedDebugInfo", reducedDebugInfo);
            compound.read("spectatorsGenerateChunks", spectatorsGenerateChunks);
            compound.read("spawnRadius", spawnRadius);
            compound.read("disablePlayerMovementCheck", disablePlayerMovementCheck);
            compound.read("disableElytraMovementCheck", disableElytraMovementCheck);
            compound.read("maxEntityCramming", maxEntityCramming);
            compound.read("doWeatherCycle", doWeatherCycle);
            compound.read("doLimitedCrafting", doLimitedCrafting);
            compound.read("maxCommandChainLength", maxCommandChainLength);
            compound.read("maxCommandForkCount", maxCommandForkCount);
            compound.read("commandModificationBlockLimit", commandModificationBlockLimit);
            compound.read("announceAdvancements", announceAdvancements);
            compound.read("disableRaids", disableRaids);
            compound.read("doInsomnia", doInsomnia);
            compound.read("doImmediateRespawn", doImmediateRespawn);
            compound.read("playersNetherPortalDefaultDelay", playersNetherPortalDefaultDelay);
            compound.read("playersNetherPortalCreativeDelay", playersNetherPortalCreativeDelay);
            compound.read("drowningDamage", drowningDamage);
            compound.read("fallDamage", fallDamage);
            compound.read("fireDamage", fireDamage);
            compound.read("freezeDamage", freezeDamage);
            compound.read("doPatrolSpawning", doPatrolSpawning);
            compound.read("doTraderSpawning", doTraderSpawning);
            compound.read("doWardenSpawning", doWardenSpawning);
            compound.read("forgiveDeadPlayers", forgiveDeadPlayers);
            compound.read("universalAnger", universalAnger);
            compound.read("playersSleepingPercentage", playersSleepingPercentage);
            compound.read("blockExplosionDropDecay", blockExplosionDropDecay);
            compound.read("mobExplosionDropDecay", mobExplosionDropDecay);
            compound.read("tntExplosionDropDecay", tntExplosionDropDecay);
            compound.read("snowAccumulationHeight", snowAccumulationHeight);
            compound.read("waterSourceConversion", waterSourceConversion);
            compound.read("lavaSourceConversion", lavaSourceConversion);
            compound.read("globalSoundEvents", globalSoundEvents);
            compound.read("doVinesSpread", doVinesSpread);
            compound.read("enderPearlsVanishOnDeath", enderPearlsVanishOnDeath);
            compound.read("minecartMaxSpeed", minecartMaxSpeed);
            compound.read("spawnChunkRadius", spawnChunkRadius);
        }
    };
    
}
